# Generated by Django 5.1.7 on 2025-04-13 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Contact',
        ),
    ]
