# Generated by Django 5.1.7 on 2025-06-08 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0007_contact_user_profile'),
        ('user_auth_app', '0006_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_auth_app.userprofile'),
        ),
    ]
