# Generated by Django 5.1.7 on 2025-06-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0004_guestuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestUser',
        ),
    ]
